### ISSUE TITLE
[Bug] Expo EAS build is failing for only Android

### ISSUE THREAD

**Issue by shebinleo** [creativetimofficial/ct-now-ui-pro-react-native#8]
### Version
1.6.1
### Reproduction link
https://jsbin.com/puhofetoze/edit?html,output
### Operating System
EAS
### Device
Android
### Browser & Version
-
### Steps to reproduce
eas build --platform android
### What is expected?
Build android app using the Expo EAS
### What is actually happening?
Error in the "Run gradlew" step. Error log can be found here https://jsbin.com/puhofetoze/edit?html,output

Creating new worker instance
Intel, 4 vCPUs, 16 GB RAM
Using image "ubuntu-20.04-jdk-11-ndk-21.4.7075529" based on "ubuntu-2004-focal-v20220823"
Installed software:
- NDK 21.4.7075529
- Node.js 16.18.1
- Bun 1.0.2
- Yarn 1.22.17
- pnpm 7.0.0
- npm 8.1.2
- Java 11
No `image` was explicitly specified. Resolved builder image to 'ubuntu-20.04-jdk-11-ndk-r21e'.
- Expo CLI 6.3.10

---
### Solution
iOS buld using eas build --platform ios is working fine.

**Comment by Jarred-Sumner** [comment]
Can you try updating to the latest version of Bun? I wonder if it's a bun install bug, if you're using bun install for this

**Comment by shebinleo** [comment]
@Jarred-Sumner Bun is not used in this case. Yarn is used to install the dependencies.

Below is the log from the `Install dependencies` job in the Expo build pipeline.
```
Running "yarn install" in /home/expo/workingdir/build directory

yarn install v1.22.17

info No lockfile found.
```

**Comment by shebinleo** [comment]
I have resolved the issue. It was caused due jpg image named as png.
Renaming `assets/imgs/bg5.png` to `assets/imgs/bg5.jpg` fixed it and now I able build the android app.
